In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\users\tanvi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tanvi\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tanvi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tanvi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tanvi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\tanvi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
pip install numpy

Requirement already satisfied: numpy in c:\users\tanvi\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd

In [23]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv")
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006  $13,898,119
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009   $9,451,943
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    26%
4  7,435,363 Dollars   3138627     8%
5  5,470,303 Dollars   8427816    23%
6  6,249,498 Dollars   3005116     6%
7  3,878,113 Dollars   5573830     4%
8                NaN  11901180    18%
9  5,635,276 Dollars   5453060     7%

In [24]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [25]:
empty_s = pd.Series([])
type(empty_s)
empty_s

Series([], dtype: object)

In [26]:
scalar_s = pd.Series([1])
print(scalar_s)

0    1
dtype: int64

In [27]:
scalar_s1 = pd.Series(0.2, index=[1,2,3,4])
print(scalar_s1)

1    0.2
2    0.2
3    0.2
4    0.2
dtype: float64

In [28]:
series_1 = pd.Series([2,3,4,5],index=['a','b','c','d'])
print(series_1)

a    2
b    3
c    4
d    5
dtype: int64

In [29]:
sr_index = pd.Series([1,2,3,4,5])
print(sr_index)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
sr_index[0]

np.int64(1)

In [31]:
sr_index[1]

np.int64(2)

In [32]:
sr_index[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [33]:
min(sr_index)

1

In [34]:
max(sr_index)

5

In [35]:
sr_index[sr_index>2]

2    3
3    4
4    5
dtype: int64

In [36]:
sr_1=pd.Series([1,2,3,4,5])
sr_2=pd.Series([1,2,3,4,5])
print(sr_1)
print(sr_2)

sr_sum=sr_1+sr_2
print(sr_sum)

sr_3 = pd.Series([1,2,3])
sr_sum_unequ=sr_2+sr_3
print(sr_sum_unequ)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64
0    2.0
1    4.0
2    6.0
3    NaN
4    NaN
dtype: float64

In [37]:
#DataFrame
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

In [38]:
import os
print(os.getcwd())

C:\Users\tanvi

In [39]:
lst = ['a','b','c']
print(lst)

['a', 'b', 'c']

In [46]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",nrows=2)
print(df)

   ID       Name            Industry  Inception       Revenue  \
0   1    Lamtone         IT Services       2009  $11,757,018
1   2  Stripfind  Financial Services       2010  $12,329,371

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%

In [48]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",usecols=[1])
print(df)

              Name
0          Lamtone
1        Stripfind
2  Canecorporation
3         Mattouch
4        Techdrill
5         Techline
6          Cityace
7   Kayelectronics
8          Ganzlax
9      Trantraxlax

In [49]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",usecols=[1,2,3,4])
print(df)

              Name             Industry  Inception       Revenue
0          Lamtone          IT Services       2009  $11,757,018
1        Stripfind   Financial Services       2010  $12,329,371
2  Canecorporation               Health       2012  $10,597,009
3         Mattouch          IT Services       2013  $14,026,934
4        Techdrill               Health       2009  $10,573,990
5         Techline               Health       2006  $13,898,119
6          Cityace               Health       2010   $9,254,614
7   Kayelectronics               Health       2009   $9,451,943
8          Ganzlax          IT Services       2011  $14,001,180
9      Trantraxlax  Government Services       2011  $11,088,336

In [50]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",skiprows=1)
print(df)

    1          Lamtone          IT Services  2009  $11,757,018   \
0   2        Stripfind   Financial Services  2010  $12,329,371
1   3  Canecorporation               Health  2012  $10,597,009
2   4         Mattouch          IT Services  2013  $14,026,934
3   5        Techdrill               Health  2009  $10,573,990
4   6         Techline               Health  2006  $13,898,119
5   7          Cityace               Health  2010   $9,254,614
6   8   Kayelectronics               Health  2009   $9,451,943
7   9          Ganzlax          IT Services  2011  $14,001,180
8  10      Trantraxlax  Government Services  2011  $11,088,336

   6,482,465 Dollars   5274553  30%
0    916,455 Dollars  11412916  20%
1  7,591,189 Dollars   3005820   7%
2  7,429,377 Dollars   6597557  26%
3  7,435,363 Dollars   3138627   8%
4  5,470,303 Dollars   8427816  23%
5  6,249,498 Dollars   3005116   6%
6  3,878,113 Dollars   5573830   4%
7                NaN  11901180  18%
8  5,635,276 Dollars   5453060   7%

In [51]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",index_col="ID")
print(df)

               Name             Industry  Inception       Revenue  \
ID
1           Lamtone          IT Services       2009  $11,757,018
2         Stripfind   Financial Services       2010  $12,329,371
3   Canecorporation               Health       2012  $10,597,009
4          Mattouch          IT Services       2013  $14,026,934
5         Techdrill               Health       2009  $10,573,990
6          Techline               Health       2006  $13,898,119
7           Cityace               Health       2010   $9,254,614
8    Kayelectronics               Health       2009   $9,451,943
9           Ganzlax          IT Services       2011  $14,001,180
10      Trantraxlax  Government Services       2011  $11,088,336

             Expenses    Profit Growth
ID
1   6,482,465 Dollars   5274553    30%
2     916,455 Dollars  11412916    20%
3   7,591,189 Dollars   3005820     7%
4   7,429,377 Dollars   6597557    26%
5   7,435,363 Dollars   3138627     8%
6   5,470,303 Dollars   8427816    23%
7   6,249,498 Dollars   3005116     6%
8   3,878,113 Dollars   5573830     4%
9                 NaN  11901180    18%
10  5,635,276 Dollars   5453060     7%

In [52]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",header=1)
print(df)

    1          Lamtone          IT Services  2009  $11,757,018   \
0   2        Stripfind   Financial Services  2010  $12,329,371
1   3  Canecorporation               Health  2012  $10,597,009
2   4         Mattouch          IT Services  2013  $14,026,934
3   5        Techdrill               Health  2009  $10,573,990
4   6         Techline               Health  2006  $13,898,119
5   7          Cityace               Health  2010   $9,254,614
6   8   Kayelectronics               Health  2009   $9,451,943
7   9          Ganzlax          IT Services  2011  $14,001,180
8  10      Trantraxlax  Government Services  2011  $11,088,336

   6,482,465 Dollars   5274553  30%
0    916,455 Dollars  11412916  20%
1  7,591,189 Dollars   3005820   7%
2  7,429,377 Dollars   6597557  26%
3  7,435,363 Dollars   3138627   8%
4  5,470,303 Dollars   8427816  23%
5  6,249,498 Dollars   3005116   6%
6  3,878,113 Dollars   5573830   4%
7                NaN  11901180  18%
8  5,635,276 Dollars   5453060   7%

In [53]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",header = None)
print(df)

     0                1                    2          3             4  \
0   ID             Name             Industry  Inception       Revenue
1    1          Lamtone          IT Services       2009  $11,757,018
2    2        Stripfind   Financial Services       2010  $12,329,371
3    3  Canecorporation               Health       2012  $10,597,009
4    4         Mattouch          IT Services       2013  $14,026,934
5    5        Techdrill               Health       2009  $10,573,990
6    6         Techline               Health       2006  $13,898,119
7    7          Cityace               Health       2010   $9,254,614
8    8   Kayelectronics               Health       2009   $9,451,943
9    9          Ganzlax          IT Services       2011  $14,001,180
10  10      Trantraxlax  Government Services       2011  $11,088,336

                    5         6       7
0            Expenses    Profit  Growth
1   6,482,465 Dollars   5274553     30%
2     916,455 Dollars  11412916     20%
3   7,591,189 Dollars   3005820      7%
4   7,429,377 Dollars   6597557     26%
5   7,435,363 Dollars   3138627      8%
6   5,470,303 Dollars   8427816     23%
7   6,249,498 Dollars   3005116      6%
8   3,878,113 Dollars   5573830      4%
9                 NaN  11901180     18%
10  5,635,276 Dollars   5453060      7%

In [54]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",names = ['A','B'])
print(df)

                                                                                        A  \
ID Name            Industry            Inception Revenue      Expenses             Profit
1  Lamtone         IT Services         2009      $11,757,018  6,482,465 Dollars   5274553
2  Stripfind       Financial Services  2010      $12,329,371  916,455 Dollars    11412916
3  Canecorporation Health              2012      $10,597,009  7,591,189 Dollars   3005820
4  Mattouch        IT Services         2013      $14,026,934  7,429,377 Dollars   6597557
5  Techdrill       Health              2009      $10,573,990  7,435,363 Dollars   3138627
6  Techline        Health              2006      $13,898,119  5,470,303 Dollars   8427816
7  Cityace         Health              2010      $9,254,614   6,249,498 Dollars   3005116
8  Kayelectronics  Health              2009      $9,451,943   3,878,113 Dollars   5573830
9  Ganzlax         IT Services         2011      $14,001,180  NaN                11901180
10 Trantraxlax     Government Services 2011      $11,088,336  5,635,276 Dollars   5453060

                                                                                      B
ID Name            Industry            Inception Revenue      Expenses           Growth
1  Lamtone         IT Services         2009      $11,757,018  6,482,465 Dollars     30%
2  Stripfind       Financial Services  2010      $12,329,371  916,455 Dollars       20%
3  Canecorporation Health              2012      $10,597,009  7,591,189 Dollars      7%
4  Mattouch        IT Services         2013      $14,026,934  7,429,377 Dollars     26%
5  Techdrill       Health              2009      $10,573,990  7,435,363 Dollars      8%
6  Techline        Health              2006      $13,898,119  5,470,303 Dollars     23%
7  Cityace         Health              2010      $9,254,614   6,249,498 Dollars      6%
8  Kayelectronics  Health              2009      $9,451,943   3,878,113 Dollars      4%
9  Ganzlax         IT Services         2011      $14,001,180  NaN                   18%
10 Trantraxlax     Government Services 2011      $11,088,336  5,635,276 Dollars      7%

In [55]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",dtype = {'ID':'float64','profit':'float64'})
print(df)

     ID             Name             Industry  Inception       Revenue  \
0   1.0          Lamtone          IT Services       2009  $11,757,018
1   2.0        Stripfind   Financial Services       2010  $12,329,371
2   3.0  Canecorporation               Health       2012  $10,597,009
3   4.0         Mattouch          IT Services       2013  $14,026,934
4   5.0        Techdrill               Health       2009  $10,573,990
5   6.0         Techline               Health       2006  $13,898,119
6   7.0          Cityace               Health       2010   $9,254,614
7   8.0   Kayelectronics               Health       2009   $9,451,943
8   9.0          Ganzlax          IT Services       2011  $14,001,180
9  10.0      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    26%
4  7,435,363 Dollars   3138627     8%
5  5,470,303 Dollars   8427816    23%
6  6,249,498 Dollars   3005116     6%
7  3,878,113 Dollars   5573830     4%
8                NaN  11901180    18%
9  5,635,276 Dollars   5453060     7%

In [56]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10 - Copy.csv")
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006      no value
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009            na
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit         Growth
0  6,482,465 Dollars   5274553            30%
1    916,455 Dollars  11412916            20%
2  7,591,189 Dollars   3005820             7%
3  7,429,377 Dollars   6597557  not available
4  7,435,363 Dollars   3138627             8%
5  5,470,303 Dollars   8427816            23%
6  6,249,498 Dollars   3005116  not available
7  3,878,113 Dollars   5573830             4%
8                NaN  11901180            18%
9  5,635,276 Dollars   5453060             7%

In [57]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10 - Copy.csv",na_values='not available')
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006      no value
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009            na
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    NaN
4  7,435,363 Dollars   3138627     8%
5  5,470,303 Dollars   8427816    23%
6  6,249,498 Dollars   3005116    NaN
7  3,878,113 Dollars   5573830     4%
8                NaN  11901180    18%
9  5,635,276 Dollars   5453060     7%

In [58]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10 - Copy.csv",na_values={'Revenue':'no values'})
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006      no value
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009            na
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit         Growth
0  6,482,465 Dollars   5274553            30%
1    916,455 Dollars  11412916            20%
2  7,591,189 Dollars   3005820             7%
3  7,429,377 Dollars   6597557  not available
4  7,435,363 Dollars   3138627             8%
5  5,470,303 Dollars   8427816            23%
6  6,249,498 Dollars   3005116  not available
7  3,878,113 Dollars   5573830             4%
8                NaN  11901180            18%
9  5,635,276 Dollars   5453060             7%

In [59]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10 - Copy.csv",keep_default_na=True)
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006      no value
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009            na
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit         Growth
0  6,482,465 Dollars   5274553            30%
1    916,455 Dollars  11412916            20%
2  7,591,189 Dollars   3005820             7%
3  7,429,377 Dollars   6597557  not available
4  7,435,363 Dollars   3138627             8%
5  5,470,303 Dollars   8427816            23%
6  6,249,498 Dollars   3005116  not available
7  3,878,113 Dollars   5573830             4%
8                NaN  11901180            18%
9  5,635,276 Dollars   5453060             7%

In [60]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10 - Copy.csv",na_filter=False)
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006      no value
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009            na
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit         Growth
0  6,482,465 Dollars   5274553            30%
1    916,455 Dollars  11412916            20%
2  7,591,189 Dollars   3005820             7%
3  7,429,377 Dollars   6597557  not available
4  7,435,363 Dollars   3138627             8%
5  5,470,303 Dollars   8427816            23%
6  6,249,498 Dollars   3005116  not available
7  3,878,113 Dollars   5573830             4%
8                     11901180            18%
9  5,635,276 Dollars   5453060             7%

In [61]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False     False   False   False
9  False  False     False      False    False     False   False   False

In [62]:
df.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True    True
3  True  True      True       True     True      True    True    True
4  True  True      True       True     True      True    True    True
5  True  True      True       True     True      True    True    True
6  True  True      True       True     True      True    True    True
7  True  True      True       True     True      True    True    True
8  True  True      True       True     True      True    True    True
9  True  True      True       True     True      True    True    True

In [63]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False     False   False   False
9  False  False     False      False    False     False   False   False

In [64]:
df.notnull().sum()

ID           10
Name         10
Industry     10
Inception    10
Revenue      10
Expenses     10
Profit       10
Growth       10
dtype: int64

In [65]:
df.notnull().sum().sum()

np.int64(80)

In [66]:
import numpy as np
ser = pd.Series([1,2,3,np.nan,4,np.nan])
ser

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [67]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [68]:
ser.notnull()

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool

In [70]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_5 nan values.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [72]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
df.dropna(how='any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [74]:
df.dropna(axis=1,how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
df.dropna(axis=1,how='all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df.dropna(thresh=2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [78]:
df.dropna(thresh=0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
df.dropna(subset = ['Profit'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [81]:
df.dropna(subset = ['Expenses'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [80]:
df.fillna({'Expenses':'none','Profit':55})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",none,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",55.0,8%
5,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
6,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
7,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
8,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
9,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN

In [82]:
df.fillna(method='ffill')

C:\Users\tanvi\AppData\Local\Temp\ipykernel_34628\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
7,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
8,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
9,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%

In [83]:
df.fillna(method='pad') #same as ffill

C:\Users\tanvi\AppData\Local\Temp\ipykernel_34628\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
7,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
8,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
9,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%

In [84]:
df.fillna(method='bfill')

C:\Users\tanvi\AppData\Local\Temp\ipykernel_34628\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","7,429,377 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
# row filling
df.fillna(method='ffill',axis=0)

C:\Users\tanvi\AppData\Local\Temp\ipykernel_34628\2876425307.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
7,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
8,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
9,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%

In [91]:
import pandas as pd
print(pd.__version__)

2.3.3

In [92]:
!python --version

Python 3.13.9

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_5 nan values.csv",na_filter=False)
print(df)

  ID             Name            Industry Inception       Revenue  \
0  1          Lamtone         IT Services      2009  $11,757,018
1  2        Stripfind  Financial Services      2010  $12,329,371
2  3  Canecorporation              Health      2012  $10,597,009
3  4         Mattouch         IT Services      2013  $14,026,934
4  5        Techdrill              Health      2009  $10,573,990
5
6
7
8
9

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2                      3005820     7%
3  7,429,377 Dollars   6597557    26%
4  7,435,363 Dollars               8%
5
6
7
8
9

In [3]:
df.fillna(method = 'ffill',limit=2,axis=1)

C:\Users\tanvi\AppData\Local\Temp\ipykernel_35132\1089467700.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill',limit=2,axis=1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009",,3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",,8%
5,,,,,,,,
6,,,,,,,,
7,,,,,,,,
8,,,,,,,,
9,,,,,,,,

In [4]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\Fortune_10.csv",na_filter=False)
print(df)

   ID             Name             Industry  Inception       Revenue  \
0   1          Lamtone          IT Services       2009  $11,757,018
1   2        Stripfind   Financial Services       2010  $12,329,371
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934
4   5        Techdrill               Health       2009  $10,573,990
5   6         Techline               Health       2006  $13,898,119
6   7          Cityace               Health       2010   $9,254,614
7   8   Kayelectronics               Health       2009   $9,451,943
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    26%
4  7,435,363 Dollars   3138627     8%
5  5,470,303 Dollars   8427816    23%
6  6,249,498 Dollars   3005116     6%
7  3,878,113 Dollars   5573830     4%
8                     11901180    18%
9  5,635,276 Dollars   5453060     7%

In [5]:
df.replace(to_replace = 'Health', value='it serv')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,it serv,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,it serv,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,it serv,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,it serv,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,it serv,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [6]:
df.replace('IT Services','AI/ML')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,AI/ML,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,AI/ML,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,AI/ML,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [7]:
df.replace(10,15)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,15,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [8]:
df.replace({'Industry':'Health'},'nan')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,nan,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,nan,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,nan,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,nan,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,nan,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [10]:
df.replace('[A-Za-z]',0,regex=True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [16]:
df.dtypes

ID            int64
Name         object
Industry     object
Inception     int64
Revenue      object
Expenses     object
Profit        int64
Growth       object
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Name       10 non-null     object
 2   Industry   10 non-null     object
 3   Inception  10 non-null     int64
 4   Revenue    10 non-null     object
 5   Expenses   10 non-null     object
 6   Profit     10 non-null     int64
 7   Growth     10 non-null     object
dtypes: int64(3), object(5)
memory usage: 772.0+ bytes

In [22]:
df.replace('[A-Za-z]','T',regex=True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,TTTTTTT,TT TTTTTTTT,2009,"$11,757,018","6,482,465 TTTTTTT",5274553,30%
1,2,TTTTTTTTT,TTTTTTTTT TTTTTTTT,2010,"$12,329,371","916,455 TTTTTTT",11412916,20%
2,3,TTTTTTTTTTTTTTT,TTTTTT,2012,"$10,597,009","7,591,189 TTTTTTT",3005820,7%
3,4,TTTTTTTT,TT TTTTTTTT,2013,"$14,026,934","7,429,377 TTTTTTT",6597557,26%
4,5,TTTTTTTTT,TTTTTT,2009,"$10,573,990","7,435,363 TTTTTTT",3138627,8%
5,6,TTTTTTTT,TTTTTT,2006,"$13,898,119","5,470,303 TTTTTTT",8427816,23%
6,7,TTTTTTT,TTTTTT,2010,"$9,254,614","6,249,498 TTTTTTT",3005116,6%
7,8,TTTTTTTTTTTTTT,TTTTTT,2009,"$9,451,943","3,878,113 TTTTTTT",5573830,4%
8,9,TTTTTTT,TT TTTTTTTT,2011,"$14,001,180",,11901180,18%
9,10,TTTTTTTTTTT,TTTTTTTTTT TTTTTTTT,2011,"$11,088,336","5,635,276 TTTTTTT",5453060,7%

In [23]:
df.replace('Health',method='ffill')

C:\Users\tanvi\AppData\Local\Temp\ipykernel_35132\3424027052.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace('Health',method='ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Financial Services,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,IT Services,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,IT Services,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,IT Services,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,IT Services,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [24]:
df.replace('Financial Services',method='ffill')

C:\Users\tanvi\AppData\Local\Temp\ipykernel_35132\2998196807.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace('Financial Services',method='ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,IT Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [29]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\student_results - copy.csv")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.0,2.0,9.0,3.0,5,50.0
1,1002,10.0,6.0,8.0,2.0,0,80.0
2,1003,10.0,NaN,NaN,2.0,4,60.0
3,1004,11.0,NaN,NaN,1.0,5,45.0
4,1005,11.0,NaN,NaN,2.0,0,NaN
5,1006,11.0,10.0,7.0,0.0,0,NaN
6,1007,NaN,4.0,6.0,0.0,0,NaN
7,1008,NaN,10.0,NaN,NaN,0,90.0
8,1009,12.0,2.0,8.0,2.0,4,60.0
9,1010,12.0,6.0,9.0,1.0,0,85.0

In [30]:
df.interpolate()

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [31]:
df.interpolate(method='linear')

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10.000000,2.0,9.00,3.0,5,50.00
1,1002,10.000000,6.0,8.00,2.0,0,80.00
2,1003,10.000000,7.0,7.75,2.0,4,60.00
3,1004,11.000000,8.0,7.50,1.0,5,45.00
4,1005,11.000000,9.0,7.25,2.0,0,56.25
5,1006,11.000000,10.0,7.00,0.0,0,67.50
6,1007,11.333333,4.0,6.00,0.0,0,78.75
7,1008,11.666667,10.0,7.00,1.0,0,90.00
8,1009,12.000000,2.0,8.00,2.0,4,60.00
9,1010,12.000000,6.0,9.00,1.0,0,85.00

In [33]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\student_results - copy.csv",parse_dates=['Study hrs'],index_col='Class')
df

C:\Users\tanvi\AppData\Local\Temp\ipykernel_35132\2639067051.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(r"C:\Users\tanvi\Downloads\student_results - copy.csv",parse_dates=['Study hrs'],index_col='Class')

,Student ID,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,
10.0,1001,2,9.0,3.0,5,50.0
10.0,1002,6,8.0,2.0,0,80.0
10.0,1003,NaN,NaN,2.0,4,60.0
11.0,1004,NaN,NaN,1.0,5,45.0
11.0,1005,NaN,NaN,2.0,0,NaN
11.0,1006,10,7.0,0.0,0,NaN
NaN,1007,4,6.0,0.0,0,NaN
NaN,1008,10,NaN,NaN,0,90.0
12.0,1009,2,8.0,2.0,4,60.0
12.0,1010,6,9.0,1.0,0,85.0

import pandas as pd

In [36]:
df = pd.read_csv(r"C:\Users\tanvi\Downloads\student_results.xls")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [37]:
#loc and iloc
df.loc[:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [38]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [39]:
df.loc[1]

Student ID                1002
Class                       10
Study hrs                    6
Sleeping hrs                 8
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  80
Name: 1, dtype: int64

In [40]:
df.loc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

In [41]:
df.loc[[2,4]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
2,1003,10,3,8,2,4,60
4,1005,11,4,7,2,0,75

In [43]:
df.loc[4,'Class']

np.int64(11)

In [44]:
df.loc[0:3,'Class']

0    10
1    10
2    10
3    11
Name: Class, dtype: int64

In [47]:
df.loc[0:2,'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [48]:
df.loc[df['Class']<11]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60

In [49]:
df.loc[df['Class']<11,['Percantege']]

   Percantege
0          50
1          80
2          60

In [52]:
df.loc[df['Social Media usage hrs']<2,['Percantege']]

   Percantege
3          45
5          96
6          80
9          85

In [53]:
#integer location base indexing
df.iloc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [54]:
df.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [55]:
# all rows of index
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [56]:
df.iloc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80